### PR TITLE
fix: automatic checks file filter to be exclusion only to keep it simple

### LINKED ISSUE #83: fix: missing pkg dependency of @sa11y/common
`@sa11y/common` is listed as a dev dependency of `@sa11y/format` because initially only common types declared in that pkg were being used in Typescript.
But currently non-type declarations from the common pkg are being used (e.g. `errMsgHeader`).  This results in error when trying to install `@sa11y/format` on its own.

The pkg dependency checker in place has failed to catch this.
- [ ] Fix the missing dependency 
- [ ] Install all @sa11y pkgs in isolation and fix any dependency issues
- [ ] Automate this check as much as possible

### PR DESCRIPTION
**Pull request by mohanraj-r**
### Bug Fixes 🐛 

* automatic checks file filter to be exclusion only to keep it simple
  *  the filter was trying to do both inclusion and exclusion which led to complicated buggy code 
* add sa11y common pkg as dep instead of dev dep (fixes #83)

### CODE REVIEW

**Review by venkatasadineni — DISMISSED** [review]

**Comment by venkatasadineni** [comment]
Looks Good To Me

File: packages/jest/src/automatic.ts [hunk 1]
```diff
@@ -34,33 +34,34 @@ const defaultAutoCheckOpts: AutoCheckOpts = {
...
-        opts.filesFilter?.length &&
-        !opts.filesFilter
-            // Convenience shortcut converting '!' prefix to filename
-            // as negative lookahead assertion regex
-            .map((filename) => (filename.startsWith('!') ? `/(?!${filename})$` : filename))
-            .some((fileName) => RegExp(fileName).test(testPath))
-    ) {
+export function skipTest(testPath: string, filesFilter?: string[]): boolean {
+    if (!filesFilter || !(filesFilter?.length > 0)) return false;
+    const skipTest = filesFilter.some((fileName) => RegExp(fileName).test(testPath));
```
Comment (trevor-bliss) [inline packages/jest/src/automatic.ts:41]: Do we expect the filesFilter entries to be the full file paths? If so, it's probably better to do a string comparison (if not === then a startsWith or contains or similar) instead of using a regex. I see how regex made sense before since we let them use the `!` negation, but to only exclude specific file paths I think a full regex is a little heavy handed.

**Review by trevor-bliss — APPROVED** [review]
